### ISSUE TITLE
服务器没人时ping会报错

### ISSUE THREAD

**Issue by Duck15** [ATFGK/PingForTShock#1]
```
ping
Server执行了/ping。
Ping 失败.
Unhandled exception
System.UnhandledExceptionEventArgs
[Server API] Error ===================================================================================
[Server API] Error An unhandled exception has occured in TSAPI, and a crash report will be generated
[Server API] Error Generating a crash report, please wait...
: [Server API] Error Could not generate a crash report.
[Server API] Error Please upload the crash file and report it at http://tshock.co/
[Server API] Error The process will terminate.
[Server API] Error ===================================================================================
================
2023/7/15 上午11:24:11: Unhandled Exception
Thread: 12 [.NET ThreadPool Worker]
Culture: zh-Hans
Exception: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at TestPlugin.TestPlugin.PingC(CommandArgs args)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
HResult: -2146233080
================
```

**Comment by Duck15** [comment]
系统:Debian 11 Linux 5.10.0 
dotnet环境 :6.0.405

**Comment by ATFGK** [comment]
可是，如果服务器没有人，为什么需要ping？

**Comment by Duck15** [comment]
> 可是，如果服务器没有人，为什么需要ping？

阿巴阿巴
我试了下，发现有人时也报错（）
报错一样，
系统是linux x86
我下源码编译的
只扔了ping.dll文件进serverplugins里
